### PR TITLE
move flux auth to role binding templates

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/giantswarm/issues/27708

This PR does not introduce any new functionality. It just moves the flux related role binding creation from the org namespace and cluster namespace controllers to a role binding template that is created within the default controller (since rbt is not namespaced)

## Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] If the change introduces new roles, please consider adding user-friendly descriptions to the roles with the annotation [giantswarm.io/notes](https://github.com/giantswarm/k8smetadata/blob/dff3b2358977e13c90479c66e21c728a96ddfe6d/pkg/annotation/general.go#L12) to help explain their purpose and usage.

### CODE REVIEW

**Review by vvondruska — APPROVED** [review]
Overall it looks good to me.
Maybe it's just a bit unfortunate that the fluxauth logic needs to be split between 2 controllers, but I am not entirely sure if there is a way to solve it (by moving the entire logic into a single controller or otherwise)

**Comment by anvddriesch** [comment]
it used to be split between two controllers but now it's just in one :)

**Comment by vvondruska** [comment]
Then I guess I am missing something. 
I see fluxauth in the `rbac` and `defaultnamespace` controllers. The one in `defaultnamespace` creates role bindings (role binding templtes) directly related to Flux. The one in `rbac` ensures creation of the Automation SA in the namespace and gives it cluster-wide permissions to write silences. If it's not directly related to Flux, then maybe we could consider renaming the resource in `rbac` to something else than `fluxauth`.

**Review by mogottsch — APPROVED** [review]

**Comment by anvddriesch** [comment]
Ohh that's what you mean. That's true. I can rename the resource.

**Pull request merged**
