### PR TITLE
Remove FluxCD resources from the read-all ClusterRole

### PR DESCRIPTION
**Pull request by ljakimczuk**
## Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] If the change introduces new roles, please consider adding user-friendly descriptions to the roles with the annotation [giantswarm.io/notes](https://github.com/giantswarm/k8smetadata/blob/dff3b2358977e13c90479c66e21c728a96ddfe6d/pkg/annotation/general.go#L12) to help explain their purpose and usage.

### CODE REVIEW

**Review by anvddriesch — COMMENTED** [review]
I think it might be cleaner to have two booleans here.
e.g.
```
if isRestrictedResource(resource.Name)|| isRestrictedGroup(gv.Group)
```

**Comment by marians** [comment]
@ljakimczuk Why is this being removed?

**Comment by ljakimczuk** [comment]
@marians it currently makes the GitOps UI Server to throw errors. The GOUIS  impersonates user who logs in, but customers do not have full permissions to the protected namespaces, and hence they can't read Secrets in there, but Secrets are where the Helm keeps releases' manifests in. This is like running the `helm list` command, what you really get as an output is the list of Kubernetes Secrets. In the Flux world the Kubernetes Secrets are still the carrier for the release, but now the whole thing is abstracted by the `HelmRelease` CR the Secret is coupled with. And hence, the GOUIS when displaying this CR it tries to get the Secret as well and complains on not being able to do so.

And now, while I am not able to say if this is error on the GOUIS side, but even if, it will take time to locate the problem, fix it there and even more time to have this change deployed in our clusters, and for the time being it may degrade user experience greatly. So my idea was to take away read permissions from user to the Flux resources, in hope the server recognizes it has no rights to operate in the protected namespace, and hence skipps it. If this helps, it should be safe to do, because users have admin permissions in their namespaces, like `default`, `org-*`, and clusters-related.

**Comment by marians** [comment]
Thanks for the explanation!

In general, removing more resources amplifies the problem that the role named "read-all" does not actually give read permission to _all_ resources.

To make this clear, please update the description in https://github.com/giantswarm/rbac-operator/blob/v0.33.1/service/controller/defaultnamespace/resource/clusterroles/create.go#L133 which is displayed in happa.

image

**Review by kubasobon — APPROVED** [review]

**Comment by ljakimczuk** [comment]
Thanks @marians! I will remember that, but for now I am going to close this after all, for after running an investigation against the GOUIS yesterday, I now believe limiting this may not help after all. I could have rushed too quickly into solution, sorry for the noise, I will come back if I have something solid.

**Comment by marians** [comment]
@ljakimczuk No worries, thanks!

**Pull request closed without merging**
